Print  "'True and True' is True."
Print  "'False and True' is False"
Print  "'1 == 1 and 2 == 1' is False"
Print  " 'Test' == 'Test' is True"
Print  "'1 == 1 or 2 != 1' is True"
Print  "'True and 1 == 1' is True"
Print  "'False and 0 !=0' is False"
Print  "'True or 1 == 1' is True"
Print  "'Test == testing' is False"
Print  "'1 !=0 and 2 == 1' is False"
Print  "'test' != 'testing' is True"
Print  "'test' == 1 is False"
Print  "'not (True and False)' is True"
Print  "'not (1 == 1 and 0 !=1)' is False"
Print  "'not (10 == 1 or 1000 == 1000)' is False"
Print  "'not (1 != 10 or 3 ==4)' is False"
Print  "'not ('testing' == 'testing' and 'Zed == Cool Guy')' is True"
Print  "'1 == 1 and (not ('testing' == 1 or 1==0))' is True"
Print  "'chunky' == 'bacon' and (not (3==4 or 3==3))' is False"
Print  "' 3==3 and (not (testing == testing or Python ==Fun)) is False"